"""Add doctor_id ForeignKey to Patient model

Revision ID: 2b4ba9583647
Revises: 291c29784743
Create Date: 2025-03-28 16:55:49.944795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4ba9583647'
down_revision: Union[str, None] = '291c29784743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'doctors', ['doctor_id'], ['id'])
    op.drop_column('patients', 'date_registered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_registered', sa.DATE(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'doctor_id')
    # ### end Alembic commands ###
