"""Add date_registered to patients

Revision ID: aabef733f9e6
Revises: 2b4ba9583647
Create Date: 2025-04-01 11:10:24.829306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aabef733f9e6'
down_revision: Union[str, None] = '2b4ba9583647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_registered', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'date_registered')
    # ### end Alembic commands ###
